### ISSUE TITLE
OS viability

### ISSUE THREAD

**Issue by davidcittadini** [achilleasa/gopher-os#58]
It was very interesting to watch the "Can you write an OS Kernel in Go?” presentation at the Golang UK Conference.  I have a couple of questions:

1.	When running, what was the base memory requirements for the Go Kernel?

2.	Would it be feasible to extend gopher-os so that one one day one could write “real” internet-based apps using it (which means supporting a communications stack etc).

I am kind of wondering how much effort would be required to make (2) happen…

Thanks

**Comment by achilleasa** [comment]
1) Currently, the kernel in its current form uses about 1.4M of physical memory. This number also includes the page table entries reserved by the Go memory allocator. When the allocator initializes,  it reserves a 512Gb virtual memory region (hence the need to pre-allocate page table entries) but the actual physical memory pages are allocated on-demand using copy-on-write (CoW).

2) In order to get something like a network stack (perhaps [this](https://fuchsia.googlesource.com/netstack/+/master) could be adapted to work with the kernel) working you generally need to provide a set of drivers for the net devices. 

    However, before starting to write drivers you need to have a mechanism to deal with hardware detection / resource allocation. To this end, I am currently working on adding ACPI support to the kernel. Unfortunately, this is quite an undertaking given that the reference ACPI implementation [provided](https://acpica.org) by Intel cannot be used as-is (it's written in C and gopher-os does not use gccgo) and therefore I have to roll my own implementation in Go.

    Once ACPI support lands in gopher-os, writing drivers for PnP hardware should become easier; I believe it should be possible to port an existing Linux net driver such as the one for E1000 which seems to be well-documented and supported by most VM environments. 

    Besides the above, to write a "real" app, the kernel needs to provide at least some services such as: task scheduling (go-routines + a running GC), a time-keeping system and potentially a sort of translation layer so that apps can use the standard library (e.g. to run an HTTP server). All of these sub-goals are included in the project's [STATUS](https://github.com/achilleasa/gopher-os/blob/master/STATUS.md) page.

   So, to answer your question: quite a bit of effort is required to get there. Also, keep in mind that I am currently working on the project on my free time. Hopefully, as the kernel becomes more mature, more people will get interested in the project and decide to contribute to it.

**Comment by davidcittadini** [comment]
Thank you.  That is an excellent, well-written answer that fully addresses my questions.  I will do more research but there is a possibility that I may help with this project, I will let you know.
