### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by sgeisbacher** [achilleasa/gopher-os#73]
first of all: i love this project 😍 👍
i have 10 years experience in higher-level-stuff (java, golang, nodejs, python, haskell, ...) and i want to go deeper now and think this is a good project to learn. 

is there an isolated component that i can work on and contribute to this project? i just need some little guidance, please 😬

thx

**Comment by sgeisbacher** [comment]
i tried to register a interrupt-handler for keyboard-interrrupts via 
`gate.HandleInterrupt(InterruptNumber(1), 0, keyboardInterruptHandler)`
 but cant get it working. any idea what i'm doing wrong?

**Comment by achilleasa** [comment]
Hi there, apologies for the late response. In terms of ideas for contributing please take a look at the [roadmap](https://github.com/achilleasa/gopher-os/blob/master/STATUS.md) document. I think a better approach to managing the roadmap would be to open enhancement/help wanted issues so people who are interested in contributing to the project can better coordinate. Let me know if you think this would help.

As to your keyboard handler question, I guess we need to implement a driver for the [APIC](https://wiki.osdev.org/APIC) first so we can route IRQ 1. Is this something that you would be interested in working on?

**Comment by sgeisbacher** [comment]
hi! yeah the "help wanted" labeled issues would definitely help to explicitly show people that and how they should/could contribute and to make coordination much easier. 👍

keyboard driver: as i already mentioned i'm not really expierenced with all that low-level stuff, but i worked through the amazing "[Write Your Own Operating System (C++)](https://www.youtube.com/watch?v=1rnA6wpF0o4&list=PLHh55M_Kq4OApWScZyPl5HhgsTJS9MZ6M)" video-series ([source](https://github.com/AlgorithMan-de/wyoos)) and so i already successfully did PIC-communication and keyboard-driver in C++ for VBox-Keyboard (not USB). and i loved it. and i would love to try to contribute PIC driver to this project, but i need some rough guidance to get started 😬

**Comment by achilleasa** [comment]
I am currently working on tasks/kernel threads/scheduling so having a working PIC (and by extension PIC-based timer) driver would allow me to get things up and running much faster.

In terms of a PIC (and/or APIC) driver I think the easiest approach is to implement the [Driver](https://github.com/achilleasa/gopher-os/blob/master/src/gopheros/device/driver.go) interface and add your driver code into a `device/irq` (or irqchip which linux uses) package. You then need to define a probe function so that the hal package can detect the chip and an init block to register the driver (for an example check out the fb detection code here: https://github.com/achilleasa/gopher-os/blob/master/src/gopheros/device/video/console/vesa_fb.go#L587-L608).

PS: To get the keyboard stuff up and running you will also need to:
- remap the PIC base offset (the default configuration has an overlap with the interrupts used by the CPU for exceptions) to a higher range (so the keyboard interrupt would actually trigger int `base + 1`).
- [enable](https://github.com/achilleasa/gopher-os/blob/master/src/gopheros/kernel/cpu/cpu_amd64.go#L8) interrupts after the kernel init code (I think they are still off when the kernel boots)

Another reference that you can use is [this](https://docs.rs/crate/pic8259_simple/0.1.1/source/src/lib.rs) well-documented rust crate for dealing with the PIC .

**Comment by sgeisbacher** [comment]
ok, i'll try to tackle that one (APIC-Driver). should i create a seperate issue for that or just go with this one here?

**Comment by achilleasa** [comment]
I would recommend to close this issue and open a new one so we can track it better.
